trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Terraform_Deployment
    displayName: 'Deploy AKS Cluster'
    jobs:
      - job: Terraform_Init
        displayName: 'Initialize Terraform'
        steps:
          - checkout: self

          # Reference the Terraform Init Template
          - template: terraform-init-template.yml
            parameters:
              resourceGroup:  var.backendRG"            
              storageAccount: var.backenstorage       
              containerName: 'terraformstate'              
              stateFileName: 'terraform.tfstate'           
              azureServiceConnection: 'YourAzureServiceConnection'

          # Reference the Terraform Validate and Plan Template
          - template: terraform-plan-template.yml
            parameters:
              azureServiceConnection: 'YourAzureServiceConnection'

          # Reference the Terraform Apply Template
          - template: terraform-apply-template.yml
            parameters:
              azureServiceConnection: 'YourAzureServiceConnection'

              