trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Terraform_Deployment
    displayName: 'Deploy AKS Cluster'
    jobs:
      - job: Terraform_Init
        displayName: 'Initialize Terraform'
        steps:
          - checkout: self

          # Reference the Terraform Init Template
          - template: pipeline-templates/stages/terraform-init.yaml
            parameters:
              resourceGroup:  var.backendRG"            
              storageAccount: var.backenstorage       
              containerName: 'terraformstate'              
              stateFileName: 'terraform.tfstate'           
              azureServiceConnection: 'YourAzureServiceConnection'

          # Reference the Terraform Validate and Plan Template
          - template: pipeline-templates/stages/terraform-validate.yaml
            parameters:
              azureServiceConnection: 'YourAzureServiceConnection'

          # Reference the Terraform Apply Template
          - template: pipeline-templates/stages/terraform-apply.yaml
            parameters:
              azureServiceConnection: 'YourAzureServiceConnection'

              